services:
  archon-server:
    build:
      context: ./python
      dockerfile: Dockerfile.server
      args:
        BUILDKIT_INLINE_CACHE: 1
        ARCHON_SERVER_PORT: '${ARCHON_SERVER_PORT:-8181}'
    container_name: archon-server-ug8404os0k8cks0soc8o4ggs-033921687373
    ports:
      - '${ARCHON_SERVER_PORT:-8181}:${ARCHON_SERVER_PORT:-8181}'
    environment:
      SUPABASE_URL: '${SUPABASE_URL}'
      SUPABASE_SERVICE_KEY: '${SUPABASE_SERVICE_KEY}'
      OPENAI_API_KEY: '${OPENAI_API_KEY:-}'
      LOGFIRE_TOKEN: '${LOGFIRE_TOKEN:-}'
      SERVICE_DISCOVERY_MODE: docker_compose
      LOG_LEVEL: '${LOG_LEVEL:-INFO}'
      ARCHON_SERVER_PORT: '${ARCHON_SERVER_PORT:-8181}'
      ARCHON_MCP_PORT: '${ARCHON_MCP_PORT:-8051}'
      ARCHON_AGENTS_PORT: '${ARCHON_AGENTS_PORT:-8052}'
      BUILDKIT_INLINE_CACHE: 1
      COOLIFY_BRANCH: '"feature-COOLIFY-compat"'
      COOLIFY_RESOURCE_UUID: ug8404os0k8cks0soc8o4ggs
      COOLIFY_CONTAINER_NAME: archon-server-ug8404os0k8cks0soc8o4ggs-033921687373
      SERVICE_URL_ARCHON-SERVER: 'https://archon-api.tanksterai.com'
      SERVICE_FQDN_ARCHON-SERVER: archon-api.tanksterai.com
      SERVICE_URL_ARCHON-MCP: 'https://archon-mcp.tanksterai.com'
      SERVICE_FQDN_ARCHON-MCP: archon-mcp.tanksterai.com
      SERVICE_URL_ARCHON-AGENTS: 'https://archon-agents.tanksterai.com'
      SERVICE_FQDN_ARCHON-AGENTS: archon-agents.tanksterai.com
      SERVICE_URL_FRONTEND: 'https://archon.tanksterai.com'
      SERVICE_FQDN_FRONTEND: archon.tanksterai.com
      COOLIFY_URL: 'https://archon-api.tanksterai.com'
      COOLIFY_FQDN: archon-api.tanksterai.com
    networks:
      app-network: null
      ug8404os0k8cks0soc8o4ggs: null
      coolify: null
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/data/coolify/applications/ug8404os0k8cks0soc8o4ggs/python/src:/app/src'
      - '/data/coolify/applications/ug8404os0k8cks0soc8o4ggs/python/tests:/app/tests'
    command:
      - python
      - '-m'
      - uvicorn
      - 'src.server.main:socket_app'
      - '--host'
      - 0.0.0.0
      - '--port'
      - '${ARCHON_SERVER_PORT:-8181}'
      - '--reload'
    healthcheck:
      test:
        - CMD
        - sh
        - '-c'
        - 'python -c "import urllib.request; urllib.request.urlopen(''http://localhost:${ARCHON_SERVER_PORT:-8181}/health'')"'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=5
      - coolify.type=application
      - coolify.name=archon-server-ug8404os0k8cks0soc8o4ggs-033921687373
      - coolify.resourceName=rishitankarchon
      - coolify.projectName=archon-os
      - coolify.serviceName=rishitankarchon
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-archon-server.entryPoints=http
      - traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-archon-server.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-archon-server.rule=Host(`archon-api.tanksterai.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-server.entryPoints=https
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-server.middlewares=gzip
      - 'traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-server.rule=Host(`archon-api.tanksterai.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-server.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-server.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://archon-api.tanksterai.com'
      - caddy_ingress_network=ug8404os0k8cks0soc8o4ggs
  archon-mcp:
    build:
      context: ./python
      dockerfile: Dockerfile.mcp
      args:
        BUILDKIT_INLINE_CACHE: 1
        ARCHON_MCP_PORT: '${ARCHON_MCP_PORT:-8051}'
    container_name: archon-mcp-ug8404os0k8cks0soc8o4ggs-033921730457
    ports:
      - '${ARCHON_MCP_PORT:-8051}:${ARCHON_MCP_PORT:-8051}'
    environment:
      SUPABASE_URL: '${SUPABASE_URL}'
      SUPABASE_SERVICE_KEY: '${SUPABASE_SERVICE_KEY}'
      LOGFIRE_TOKEN: '${LOGFIRE_TOKEN:-}'
      SERVICE_DISCOVERY_MODE: docker_compose
      TRANSPORT: sse
      LOG_LEVEL: '${LOG_LEVEL:-INFO}'
      API_SERVICE_URL: 'http://archon-server:${ARCHON_SERVER_PORT:-8181}'
      AGENTS_SERVICE_URL: 'http://archon-agents:${ARCHON_AGENTS_PORT:-8052}'
      ARCHON_MCP_PORT: '${ARCHON_MCP_PORT:-8051}'
      ARCHON_SERVER_PORT: '${ARCHON_SERVER_PORT:-8181}'
      ARCHON_AGENTS_PORT: '${ARCHON_AGENTS_PORT:-8052}'
      BUILDKIT_INLINE_CACHE: 1
      COOLIFY_BRANCH: '"feature-COOLIFY-compat"'
      COOLIFY_RESOURCE_UUID: ug8404os0k8cks0soc8o4ggs
      COOLIFY_CONTAINER_NAME: archon-mcp-ug8404os0k8cks0soc8o4ggs-033921730457
      SERVICE_URL_ARCHON-SERVER: 'https://archon-api.tanksterai.com'
      SERVICE_FQDN_ARCHON-SERVER: archon-api.tanksterai.com
      SERVICE_URL_ARCHON-MCP: 'https://archon-mcp.tanksterai.com'
      SERVICE_FQDN_ARCHON-MCP: archon-mcp.tanksterai.com
      SERVICE_URL_ARCHON-AGENTS: 'https://archon-agents.tanksterai.com'
      SERVICE_FQDN_ARCHON-AGENTS: archon-agents.tanksterai.com
      SERVICE_URL_FRONTEND: 'https://archon.tanksterai.com'
      SERVICE_FQDN_FRONTEND: archon.tanksterai.com
      COOLIFY_URL: 'https://archon-mcp.tanksterai.com'
      COOLIFY_FQDN: archon-mcp.tanksterai.com
    networks:
      app-network: null
      ug8404os0k8cks0soc8o4ggs: null
      coolify: null
    depends_on:
      - archon-server
      - archon-agents
    healthcheck:
      test:
        - CMD
        - sh
        - '-c'
        - 'python -c "import socket; s=socket.socket(); s.connect((''localhost'', ${ARCHON_MCP_PORT:-8051})); s.close()"'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=5
      - coolify.type=application
      - coolify.name=archon-mcp-ug8404os0k8cks0soc8o4ggs-033921730457
      - coolify.resourceName=rishitankarchon
      - coolify.projectName=archon-os
      - coolify.serviceName=rishitankarchon
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-archon-mcp.entryPoints=http
      - traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-archon-mcp.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-archon-mcp.rule=Host(`archon-mcp.tanksterai.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-mcp.entryPoints=https
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-mcp.middlewares=gzip
      - 'traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-mcp.rule=Host(`archon-mcp.tanksterai.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-mcp.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-mcp.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://archon-mcp.tanksterai.com'
      - caddy_ingress_network=ug8404os0k8cks0soc8o4ggs
  archon-agents:
    build:
      context: ./python
      dockerfile: Dockerfile.agents
      args:
        BUILDKIT_INLINE_CACHE: 1
        ARCHON_AGENTS_PORT: '${ARCHON_AGENTS_PORT:-8052}'
    container_name: archon-agents-ug8404os0k8cks0soc8o4ggs-033921736885
    ports:
      - '${ARCHON_AGENTS_PORT:-8052}:${ARCHON_AGENTS_PORT:-8052}'
    environment:
      SUPABASE_URL: '${SUPABASE_URL}'
      SUPABASE_SERVICE_KEY: '${SUPABASE_SERVICE_KEY}'
      OPENAI_API_KEY: '${OPENAI_API_KEY:-}'
      LOGFIRE_TOKEN: '${LOGFIRE_TOKEN:-}'
      SERVICE_DISCOVERY_MODE: docker_compose
      LOG_LEVEL: '${LOG_LEVEL:-INFO}'
      ARCHON_AGENTS_PORT: '${ARCHON_AGENTS_PORT:-8052}'
      BUILDKIT_INLINE_CACHE: 1
      COOLIFY_BRANCH: '"feature-COOLIFY-compat"'
      COOLIFY_RESOURCE_UUID: ug8404os0k8cks0soc8o4ggs
      COOLIFY_CONTAINER_NAME: archon-agents-ug8404os0k8cks0soc8o4ggs-033921736885
      SERVICE_URL_ARCHON-SERVER: 'https://archon-api.tanksterai.com'
      SERVICE_FQDN_ARCHON-SERVER: archon-api.tanksterai.com
      SERVICE_URL_ARCHON-MCP: 'https://archon-mcp.tanksterai.com'
      SERVICE_FQDN_ARCHON-MCP: archon-mcp.tanksterai.com
      SERVICE_URL_ARCHON-AGENTS: 'https://archon-agents.tanksterai.com'
      SERVICE_FQDN_ARCHON-AGENTS: archon-agents.tanksterai.com
      SERVICE_URL_FRONTEND: 'https://archon.tanksterai.com'
      SERVICE_FQDN_FRONTEND: archon.tanksterai.com
      COOLIFY_URL: 'https://archon-agents.tanksterai.com'
      COOLIFY_FQDN: archon-agents.tanksterai.com
    networks:
      app-network: null
      ug8404os0k8cks0soc8o4ggs: null
      coolify: null
    healthcheck:
      test:
        - CMD
        - sh
        - '-c'
        - 'python -c "import urllib.request; urllib.request.urlopen(''http://localhost:${ARCHON_AGENTS_PORT:-8052}/health'')"'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=5
      - coolify.type=application
      - coolify.name=archon-agents-ug8404os0k8cks0soc8o4ggs-033921736885
      - coolify.resourceName=rishitankarchon
      - coolify.projectName=archon-os
      - coolify.serviceName=rishitankarchon
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-archon-agents.entryPoints=http
      - traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-archon-agents.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-archon-agents.rule=Host(`archon-agents.tanksterai.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-agents.entryPoints=https
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-agents.middlewares=gzip
      - 'traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-agents.rule=Host(`archon-agents.tanksterai.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-agents.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-archon-agents.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://archon-agents.tanksterai.com'
      - caddy_ingress_network=ug8404os0k8cks0soc8o4ggs
  frontend:
    build: ./archon-ui-main
    container_name: frontend-ug8404os0k8cks0soc8o4ggs-033921742493
    ports:
      - '${ARCHON_UI_PORT:-3737}:5173'
    environment:
      VITE_API_URL: 'http://${HOST:-localhost}:${ARCHON_SERVER_PORT:-8181}'
      ARCHON_SERVER_PORT: '${ARCHON_SERVER_PORT:-8181}'
      HOST: '${HOST:-localhost}'
      COOLIFY_BRANCH: '"feature-COOLIFY-compat"'
      COOLIFY_RESOURCE_UUID: ug8404os0k8cks0soc8o4ggs
      COOLIFY_CONTAINER_NAME: frontend-ug8404os0k8cks0soc8o4ggs-033921742493
      SERVICE_URL_ARCHON-SERVER: 'https://archon-api.tanksterai.com'
      SERVICE_FQDN_ARCHON-SERVER: archon-api.tanksterai.com
      SERVICE_URL_ARCHON-MCP: 'https://archon-mcp.tanksterai.com'
      SERVICE_FQDN_ARCHON-MCP: archon-mcp.tanksterai.com
      SERVICE_URL_ARCHON-AGENTS: 'https://archon-agents.tanksterai.com'
      SERVICE_FQDN_ARCHON-AGENTS: archon-agents.tanksterai.com
      SERVICE_URL_FRONTEND: 'https://archon.tanksterai.com'
      SERVICE_FQDN_FRONTEND: archon.tanksterai.com
      COOLIFY_URL: 'https://archon.tanksterai.com'
      COOLIFY_FQDN: archon.tanksterai.com
    networks:
      app-network: null
      ug8404os0k8cks0soc8o4ggs: null
      coolify: null
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:5173'
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - '/data/coolify/applications/ug8404os0k8cks0soc8o4ggs/archon-ui-main/src:/app/src'
      - '/data/coolify/applications/ug8404os0k8cks0soc8o4ggs/archon-ui-main/public:/app/public'
    depends_on:
      - archon-server
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=5
      - coolify.type=application
      - coolify.name=frontend-ug8404os0k8cks0soc8o4ggs-033921742493
      - coolify.resourceName=rishitankarchon
      - coolify.projectName=archon-os
      - coolify.serviceName=rishitankarchon
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-frontend.entryPoints=http
      - traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-frontend.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-ug8404os0k8cks0soc8o4ggs-frontend.rule=Host(`archon.tanksterai.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-frontend.entryPoints=https
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-frontend.middlewares=gzip
      - 'traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-frontend.rule=Host(`archon.tanksterai.com`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-frontend.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-ug8404os0k8cks0soc8o4ggs-frontend.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://archon.tanksterai.com'
      - caddy_ingress_network=ug8404os0k8cks0soc8o4ggs
volumes: {  }
networks:
  app-network:
    driver: bridge
  ug8404os0k8cks0soc8o4ggs:
    name: ug8404os0k8cks0soc8o4ggs
    external: true
  coolify:
    name: coolify
    external: true
configs: {  }
secrets: {  }

